language: ruby
cache: bundler
sudo: false
rvm: 2.2

before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild

script: script/cibuild
notifications:
  email:
    on_success: never
    on_failure: change
